config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :pets, only: %i[index show new create edit update] do
    scope module: :pets do
      resources :alerts, only: %i[index]
    end
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  #scope module: :chatrooms do
  #  resources :messages, only: :create
  #end

  resources :pets, only: %i[destroy]
  resources :vetos, only: %i[index]
end

app/models/alert.rb
class Alert < ApplicationRecord
  belongs_to :race
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  belongs_to :type
  belongs_to :race
end

app/models/race.rb
class Race < ApplicationRecord
  belongs_to :type
  has_many :alerts, dependent: :destroy
  has_many :pets, dependent: :destroy
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :veto
  belongs_to :services_explain
end

app/models/services_explain.rb
class ServicesExplain < ApplicationRecord
  has_many :services, dependent: :destroy
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :pets, dependent: :destroy
  has_many :races, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pets, dependent: :destroy
  has_many :messages, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/veto.rb
class Veto < ApplicationRecord
  has_many :services, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "message", locals: {message: @message})
      )
      head :ok
    else
      render "pets/index"
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def index
    @pets = current_user.pets
    @chatroom = Chatroom.find_by(name: "general")
    @message = Message.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div id="message-<%= message.id %>">
  <small>
    <strong><%= message.user.email %></strong>
    <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
  <p><%= message.content %></p>
</div>

app/views/pages/home.html.erb
<div class="container">
  <h1 class="title title_home">titre pets app</h1>

  <%= image_tag("/img/imageHome.jpg", class: "img_home ", :alt => "rss feed") %>
  <p class="title">L'App de gestion des bêtes! </p>
  <%= link_to "comencer", pets_path, class: "btn btn-primary center btn-start"%>
</div>

app/views/pets/index.html.erb
<h1 class ="title">vos pets</h1>
<%i = 1%>

<div class ="pet-cards d-flex flex-wrap">

  <% @pets.each do |pet|%>

    <div>

      <div class="pet-card m-2 d-flex flex-column">

        <!--img du pet-->
        <% type = pet.type.name %>
        <% if i <= @pets.count%>
          <%= image_tag("/img/#{type}#{i}.jpg", class: "img-pet", alt: "un joli #{type}") %>
          <%i += 1%>
        <%else%>
          <%i = 1%>
          <%= image_tag("/img/chien#{i}.jpg", class: "img-pet", alt: "un joli #{type}") %>
        <%end%>

        <!--caracte principal-->
        <strong class="mt-2 title"><%= pet.name%></strong>

        <div class="cellule-caract-principal ml-2 mr-2 d-flex flex-row justify-content-between">
          <p class="cellule-race"><%= pet.race.name%></p>
          <p><%= pet.age %><% if pet.age > 1 %> ans<%else%> an<%end%></p>
        </div>

        <p class="ml-2"><%= pet.content%></p>
      </div>


      <!--carnet de santer du pet-->
      <div class="pet-card-health m-2" data-controller="health-pet">

        <div class="d-flex flex-row justify-content-between">
          <strong><p>carnet de santé</p></strong>
          <i class="fas fa-angle-down pt-1" data-action="click->health-pet#display" data-health-pet-target="button"></i>
        </div>


        <div class="p-2 d-none" data-health-pet-target="health">
          <p class="celule-health">vaccins</p>
          <p class="celule-health">dernière visite véto</p>
          <p class="celule-health">alérgies</p>
          <p class="celule-health">régime spécial</p>
          <p >maladie connue</p>
        </div>

      </div>
    </div>
  <%end%>

  <!-- chatroom -->
  <div class="container-chatroom flex-grow">
    <%= render "components/pets/chatroom", chatroom: @chatroom, message: @message%>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "/img/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "/img/avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>